### ISSUE TITLE
remain cart state

### ISSUE THREAD

**Issue by mahotilo** [Asraf-Uddin-Ahmed/jquery.mycart#11]
I try to keep cart state on demo page reload.
As you say in readme I deleted `cartItems` field in `index.html`, but this didn't help me. 
Then I also deleted in `jquery.mycart.js`

> 25:      cartItems: [],

and all works fine for me now.

Did I do it right?

**Comment by Asraf-Uddin-Ahmed** [comment]
Yes, you did right thing. I have also added this feature in Release#1.4. Thanks for your help.
