### ISSUE TITLE
reread target?

### ISSUE THREAD

**Issue by panpyro** [Asraf-Uddin-Ahmed/jquery.mycart#12]
I like this script, but I have problems to reread the target. I load content via ajax with a click event into a div and the cart buttons in it not works. All other buttons loaded with the page working fine.
I have clone the `$target.click(function(){ … });` part and change it with:

`$(document).on("click", ".panel-group .my-cart-btn", function(e){
var id = $(this).attr("data-id");
var name = $(this).attr("data-name");
var summary = $(this).attr("data-summary");
var price = $(this).attr("data-price");
var quantity = $(this).attr("data-quantity");
var image = $(this).attr("data-image");
….`

In this mode it works for me but how I can fix it without make this bad work around?

**Comment by Asraf-Uddin-Ahmed** [comment]
This issue has been solved. Thanks for your feedback.
