### ISSUE TITLE
plugin having issue with flying image animation

### ISSUE THREAD

**Issue by vishalsingh119** [Asraf-Uddin-Ahmed/jquery.mycart#13]
Hi, i set cart icon right side of page, but onclick on add to cart btn, image flying animation is going left side of page. when we make cart icon independent mean position absolute and static, its working fine. but i cant be add absolute. any other way

**Comment by Asraf-Uddin-Ahmed** [comment]
This is not a plugin feature. I have write my own **goToCartIcon()** function in **index.html** for flying image animation. If you want it, then you have to implement yourself.
