### ISSUE TITLE
click my-cart-btn doesn't work after ajax call?

### ISSUE THREAD

**Issue by uhpone** [Asraf-Uddin-Ahmed/jquery.mycart#17]
this plugin help me a lot but after ajax call, .my-cart-btn doesn't work. any soloution? thanks!

**Comment by Asraf-Uddin-Ahmed** [comment]
This problem is arise for binding jQuery event with your **_add to cart_** button as per my understand. You should call **myCart** after appending HTML on page.

**Comment by uhpone** [comment]
Thanks. It's worked for me. Just like this.

$.ajax({
        type: 'get',
        dataType: 'html',
        url: '{{url('/productCat')}}',
        // data: 'cat_id=' + catId,
        data: 'cat_id=' + catId +'&step1CatId=null&step2CatId=null&step3CatId=null',
        success: function(response) {
          $('#productData').html(response);
          **$(".my-cart-btn").myCart(options);**
        }
      });
