### ISSUE TITLE
Block shipping checkoutCart button

### ISSUE THREAD

**Issue by JoseDevelopers** [Asraf-Uddin-Ahmed/jquery.mycart#18]
Hi Asraf,

I am trying to block the action of the "checkoutCart" button, I have to first check that certain conditions are met in my shopping cart, how could I do this?

Regards!

**Comment by Asraf-Uddin-Ahmed** [comment]
This feature is not currently available. I will add this feature soon. Thanks.

**Comment by Asraf-Uddin-Ahmed** [comment]
Please **return false** from **checkoutCart** function, that will block the default action. For detail please take a look at _checkoutCart_ in [Options](https://github.com/Asraf-Uddin-Ahmed/jquery.mycart#options).

**Comment by JoseDevelopers** [comment]
Great Asraf! many thanks for your work!!
