### ISSUE TITLE
My cart doesn't want to add more than 14 products

### ISSUE THREAD

**Issue by decoupe2psd** [Asraf-Uddin-Ahmed/jquery.mycart#23]
Hi,

I do not understand where it comes from because I have not seen an option on it but when I add products to the basket it works well until I reach 14 different products. At this moment, he does not want to add anything. I can only change the quantities of products already in the cart.

Can you help me please ?

Thx

**Comment by Asraf-Uddin-Ahmed** [comment]
This problem is fixed. Please update your jQuery.mycart.
