### ISSUE TITLE
দ্বিতীয়বার কার্টে অ্যাডের ক্ষেত্রে সমস্যা

### ISSUE THREAD

**Issue by drtanzil** [Asraf-Uddin-Ahmed/jquery.mycart#24]
সম্ভবত কার্টে ডিফল্ট প্রোডাক্ট সংখ্যা ১ দেয়া। আমি প্ল্যাগইনটা কাস্টমাইজ করে একটা প্রজেক্টে ব্যবহার করছি। 
ধরুন, প্রথমে কার্টে ১০ টা প্রোডাক্ট যোগ করা হয়। দ্বিতীয়বার ১০ দিয়ে আবার সাবমিট করলে মোট ২০ হাবার কথা কিন্তু হচ্ছে ১১.

ভাই একটু গাইড করলে সুধিবা হয় কিভাবে সেটা করা সম্ভব?

প্ল্যাগইনটা অনেক চমৎকার হয়েছে। এটার আপডেট চালিয়ে যাবেন প্রত্যাশা করছি।

**Comment by Asraf-Uddin-Ahmed** [comment]
This bug is fixed on Release # 1.8
