### ISSUE TITLE
Not an issue, all working great! Thank you!

### ISSUE THREAD

**Issue by daksamedia** [Asraf-Uddin-Ahmed/jquery.mycart#3]
Dear @Asraf-Uddin-Ahmed ,

I found this plugin on google, your works is great!
Thank you.
I got some headache working chart on jquery.
But this is wonderful, I really appreciate this.

Once again, thank you..
May Allah bless you always.

Daksa Media

**Comment by Asraf-Uddin-Ahmed** [comment]
Welcome. Thanks for your interest.
