### ISSUE TITLE
Local Storage Persistent

### ISSUE THREAD

**Issue by sitesurfer** [Asraf-Uddin-Ahmed/jquery.mycart#5]
Might be worth mentioning that if you are dynamically calling this on (on the fly generated items) then re-initializing the cart removes the local storage data.

I got around this by simply using the localstorage.data as the cart contents.

Perhaps we could have a setup var to name the local storage dump to make it persistent to a specific cart?

**Comment by diegobalado** [comment]
I could fix it adding a validation before the clearProduct at loadMyCartEvent.
(:184) `if (!localStorage.products) ProductManager.clearProduct();`
I hope it helps.
