### ISSUE TITLE
calculating bug

### ISSUE THREAD

**Issue by sanalrenk** [Asraf-Uddin-Ahmed/jquery.mycart#6]
Hello, thanks for the nice cart but there is small calculate bug but i can not fix it.

i changed like this : **data-price="11.52"** 
Please see the attachment images for details.
How can i fixed it?

Thanks.

![screen shot 2017-05-04 at 23 01 49](https://cloud.githubusercontent.com/assets/21036036/25723475/ca8a539a-3120-11e7-9d33-45062d44df75.png)
![screen shot 2017-05-04 at 23 02 12](https://cloud.githubusercontent.com/assets/21036036/25723474/ca89c592-3120-11e7-8f33-e19828d62dee.png)
![screen shot 2017-05-04 at 23 02 26](https://cloud.githubusercontent.com/assets/21036036/25723473/ca866c08-3120-11e7-8dd5-9f963153b91e.png)
![screen shot 2017-05-04 at 23 02 45](https://cloud.githubusercontent.com/assets/21036036/25723476/ca8c6ad6-3120-11e7-80fa-54a4dc0acfe4.png)

**Comment by sanalrenk** [comment]
![screen shot 2017-05-04 at 23 01 49](https://cloud.githubusercontent.com/assets/21036036/25723475/ca8a539a-3120-11e7-9d33-45062d44df75.png)
![screen shot 2017-05-04 at 23 02 12](https://cloud.githubusercontent.com/assets/21036036/25723474/ca89c592-3120-11e7-8f33-e19828d62dee.png)
![screen shot 2017-05-04 at 23 02 26](https://cloud.githubusercontent.com/assets/21036036/25723473/ca866c08-3120-11e7-8dd5-9f963153b91e.png)
![screen shot 2017-05-04 at 23 02 45](https://cloud.githubusercontent.com/assets/21036036/25723476/ca8c6ad6-3120-11e7-80fa-54a4dc0acfe4.png)

**Comment by Asraf-Uddin-Ahmed** [comment]
Thanks for your bug report. I have solved it by using _toFixed()_ function.

**Comment by sanalrenk** [comment]
Thank you it is working perfect now.

**Comment by sanalrenk** [comment]
hello,
how can I convert numbers from example:
 $15 to $15.00
or
from $15.6 to $15.60
and similar like this?

**Comment by Asraf-Uddin-Ahmed** [comment]
I have updated the plugin. Now you can set digit after decimal by using **numberOfDecimals**
