### ISSUE TITLE
shopping cart items come back after page refresh

### ISSUE THREAD

**Issue by sanalrenk** [Asraf-Uddin-Ahmed/jquery.mycart#7]
Hello friend, plugins goes to fine step by step thanks.
I found little three bug again,

1- Page loading with 4 cart items, it must be 0 items in sopping cart when page visit for first time but there is always 4 items in shopping cart.

2- And I deleted shopping cart items, if reload page still there was items in shopping cart.

3- cart prices numbers must be align to the right similar like this:
```
$   24.00
$  123.23
$   01.23
```

**Comment by Asraf-Uddin-Ahmed** [comment]
Scenario 1 - set **cartItems** option empty or ignore it to start cart from 0. **cartItems** option is used for initializing cart.

Scenario 2 - after reloading the page, cart will initialize from **cartItems** option.

Scenario 3 - I will give this feature in future. Thanks for your feedback.

**Comment by Asraf-Uddin-Ahmed** [comment]
This feature (Scenario 3) has been added
