### ISSUE TITLE
show cart without modal

### ISSUE THREAD

**Issue by tmblog** [Asraf-Uddin-Ahmed/jquery.mycart#9]
Hello Asraf, how can I show the cart without modal? I can see you can disable the modal by setting it to false in that case how do you view the cart?

**Comment by Asraf-Uddin-Ahmed** [comment]
1. Set **showCheckoutModal** to _false_.
2. Create your custom checkout page or section.
3. Use below class to take following action -
 3.1 **classProductQuantity** (_'my-product-quantity'_) to take input of product quantity
 3.2 **classProductRemove** (_'my-product-remove'_) to remove product from cart
 3.3 **classCheckoutCart** (_'my-cart-checkout'_) to checking out from cart
4. Show your custom checkout page or section while user click on **classCartIcon**(_'my-cart-icon'_).
5. Store cart data from **clickOnCartIcon** callback
6. Show the stored data in your custom checkout page
7. Initialize **myCart** by any selector

**Comment by tmblog** [comment]
Thanks for the reply. Do you have an example code? I couldn't get it working.
